channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - pip:
      - matplotlib==3.3.2
      - ipython==8.1.1
      - keras==2.8.0
      - tensorflow==2.8.0
      - numpy==1.21.5
      - pandas==1.2.3
      - pycurl==7.43.0.6
      - scikit-image==0.17.2
      - scikit-learn==0.23.2
      - scipy==1.5.2
      - seaborn==0.11.0
      - python-dotenv==0.19.2